# Generated by Django 3.2.5 on 2021-07-16 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATName', models.CharField(max_length=50, verbose_name='Name')),
                ('CATParent', models.ForeignKey(blank=True, limit_choices_to={'CATParent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.category', verbose_name='Main Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROName', models.CharField(max_length=100, verbose_name='product name')),
                ('PRDDescr', models.TextField(verbose_name='product description')),
                ('PRDPrice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='product price')),
                ('PRDImage', models.ImageField(blank=True, null=True, upload_to='productImage/', verbose_name='Imaage')),
                ('PROCost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='product Cost')),
                ('PROCreated', models.DateTimeField(verbose_name='time created')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
                ('PROCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDImage', models.ImageField(upload_to='productImage/', verbose_name='Imaage')),
                ('PROIProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.product', verbose_name='product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PALNAlternatives', models.ManyToManyField(related_name='alternative_products', to='pages.Product', verbose_name='Alternative')),
                ('PALNProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='pages.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Alternative',
                'verbose_name_plural': 'Products Alternative',
            },
        ),
        migrations.CreateModel(
            name='Product_Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PACCAlternatives', models.ManyToManyField(related_name='accessories_products', to='pages.Product', verbose_name='Accessoire')),
                ('PACCProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainAccessory_product', to='pages.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Accessory',
                'verbose_name_plural': 'Products Accessories',
            },
        ),
    ]
