# Generated by Django 3.2.4 on 2021-06-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_under',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
