# Generated by Django 3.2.4 on 2021-06-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210629_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo_author',
            field=models.ImageField(blank=True, null=True, upload_to='photos/y%/m%/d%'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_post',
            field=models.ImageField(blank=True, null=True, upload_to='photos/y%/m%/d%'),
        ),
    ]
