# Generated by Django 3.2.4 on 2021-06-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210629_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo_author',
            field=models.ImageField(blank=True, null=True, upload_to='photosblog/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_post',
            field=models.ImageField(blank=True, null=True, upload_to='photosblog/%y/%m/%d'),
        ),
    ]
