# Generated by Django 3.2.4 on 2021-06-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo_author',
            field=models.ImageField(blank=True, null=True, upload_to='photosblog'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_post',
            field=models.ImageField(blank=True, null=True, upload_to='photosblog'),
        ),
    ]
