# Generated by Django 3.2.4 on 2021-06-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210629_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo_Category',
            field=models.ImageField(blank=True, null=True, upload_to='photosblogCategory'),
        ),
    ]
