# Generated by Django 3.2.4 on 2021-06-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_category_photo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='content_category',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
